"""Reuse the checked same-session continuation mechanism for final review and ledger."""
from pathlib import Path
base=Path(__file__).with_name('resume_remaining.py')
source=base.read_text()
prompts={
'11':'''Resume SAME Batch17 review session/worktree for final bounded supplement04_08. Preserve first-stage and02 accepted artifacts. Independently review corrected B15-04/docs/b17_04_report.md and certificates (exact11-basis match; rank FLOOR9, interval9..10, not exact9) plus B15-08/docs/b17_08_report.md (five-row actual product-map rank, clipping thresholds, all-degree Jflag row exclusion). Review08's original pinned02 as historical: your supplement02 now accepts that scoped bound but supplies no numerical loss. One new independently priced60sec/512MiB control is authorized if needed, inspected original wrapper, one process/BLAS thread; no heavy lease or further research search. Write docs/b17_11_supplement04_08.md and update manifest preserving earlier deliveries. Give exact ACCEPTED/REJECTED/UNVERIFIED claims. Determine whether09/10 have any supported finite candidate;08 nominated none. Do not wait for12. Preserve Astra/xhigh, normal approvals, sandbox/ownership/trust. No agents, new worktrees, commits,push,publication.''',
'12':'''User authorized continuing Batch17 closeout after adding credits. Resume SAME ledger session, retaining Astra/xhigh, original worktree and all sandbox/approval/ownership/trust constraints. Inspect saved files and reuse successful initial checks; no scientific computation or heavy lease authorized. Read original01/02/03/04/05/06/07/08 reports and B15-11/docs/b17_11_report.md plus b17_11_supplement02.md. First-stage and02 scoped claims accepted. A final04/08 review is running; do not poll or await it. Prepare docs/b17_12_closeout.md and updated manifest as a closure-ready ledger, explicitly marking04/08 pending final review if unavailable.08 nominated no finite family, so09/10 are NOT_TRIGGERED, not failed mathematical exclusions. Separate supplementary work/capelli_cayley_investigation/expanded_repair/report.md as producer-verified, not independently accepted. No gap, no improved asymptotic size growth. Provide claim provenance, remaining theorem/computation questions, roadmap and exact final integration steps. Preserve initial report as history; fix obsolete capacity/launch descriptions in new ledger using current saved reports rather than stale02 retry log. No agents,worktrees,commits,push,publication,configuration changes. Read-only Git only with normal operation-specific approval if necessary.'''}
start=source.index('prompts={');end=source.index('# All checks before any launch.')
source=source[:start]+'prompts='+repr(prompts)+'\n'+source[end:]
exec(compile(source,str(base),'exec'),{'__file__':str(base),'__name__':'__main__'})
