# Administrative validation and local sealing only. No mathematical computation.
$ErrorActionPreference = 'Stop'
$repo = 'C:/Users/swami/Projects/gct-gpt/work/batch15'
$out = "$repo/results/a25_02"
$payload = @(
 'docs/a25_02_report.md',
 'analysis/a25_02_admin.ps1',
 'analysis/a25_02_seal.ps1',
 'results/a25_02/INTAKE.md',
 'results/a25_02/SOURCE_BINDINGS.json',
 'results/a25_02/SCOPE_MATRIX.md',
 'results/a25_02/IMPLICATIONS.md',
 'results/a25_02/APPLICATIONS.md',
 'results/a25_02/SURVIVOR_SPEC.md',
 'results/a25_02/RESOURCE_RECEIPTS.md',
 'results/a25_02/LIMITATIONS.md',
 'results/a25_02/DELIVERY_NOTE.md',
 'results/a25_02/ADD_LIST.txt'
)
$all = @($payload) + 'results/a25_02/ADMIN_VERIFICATION.json' + 'results/a25_02/MANIFEST.json'
[IO.File]::WriteAllText("$out/ADD_LIST.txt", ($all -join "`n")+"`n", [Text.UTF8Encoding]::new($false))
$head = (& git -C $repo rev-parse HEAD).Trim()
$branch = (& git -C $repo branch --show-current).Trim()
if($head -ne '82633a60893236fab4fbc317df416e1b8a349005' -or $branch -ne 'batch15-launch') { throw 'Repository state changed; inspect before sealing.' }
$checks = @()
foreach($p in $payload) {
 if(-not (Test-Path -LiteralPath "$repo/$p" -PathType Leaf)) { throw "Missing $p" }
 $raw = (& git -C $repo hash-object --no-filters -- "$repo/$p").Trim()
 $filtered = (& git -C $repo hash-object "--path=$p" -- "$repo/$p").Trim()
 $attr = @(& git -C $repo check-attr text eol filter -- $p)
 $ignored = @(& git -C $repo check-ignore -- $p 2>$null)
 $ignoreCode = $LASTEXITCODE
 if($ignoreCode -notin @(0,1)) { throw "Ignore check failed for $p" }
 if($ignoreCode -eq 0) { throw "Proposed path ignored: $p" }
 $checks += [ordered]@{path=$p; raw_blob_id=$raw; filtered_blob_id=$filtered; equal=($raw -eq $filtered); ignored=$false; attributes=$attr}
}
# Check local Markdown links in the main report; other files use source IDs.
$report = [IO.File]::ReadAllText("$repo/docs/a25_02_report.md")
$links = @()
foreach($match in [regex]::Matches($report,'\]\(([^)]+)\)')) {
 $target = $match.Groups[1].Value
 if($target -match '^(https?:|#)') {continue}
 $resolved = [IO.Path]::GetFullPath([IO.Path]::Combine("$repo/docs",$target))
 if(-not (Test-Path -LiteralPath $resolved) -and $target -notmatch '(MANIFEST.json|ADD_LIST.txt)$') { throw "Broken report link: $target" }
 $links += [ordered]@{target=$target; resolved=$resolved; verification='Exists or is a manifest generated by this seal'}
}
$verify = [ordered]@{utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ'); status='UNCOMMITTED administrative check'; head=$head; branch=$branch; file_checks=$checks; report_links=$links; global_ignore_note='Sandbox warned on global ignore access; repository-specific checks returned not ignored'; mathematical_computations=0}
$verify | ConvertTo-Json -Depth 8 | Set-Content -Encoding utf8NoBOM "$out/ADMIN_VERIFICATION.json"
$payload += 'results/a25_02/ADMIN_VERIFICATION.json'
$artifacts = foreach($p in $payload) {
 $bytes=[IO.File]::ReadAllBytes("$repo/$p")
 [ordered]@{path=$p; bytes=$bytes.Length; sha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes)).ToLowerInvariant(); status='UNCOMMITTED / NOT RELEASED'}
}
$now=[DateTime]::UtcNow
$manifest=[ordered]@{
 schema='a25_02.local_packet.v1'; slot='A25-02'; outcome=1;
 status='LOCAL COMPLETE / UNCOMMITTED / NOT RELEASED'; delivery_commit=$null;
 repository=$repo; branch=$branch; research_head=$head;
 assessment_started_utc='2026-09-21T00:44:57Z'; framework_frozen_by_utc='2026-09-21T00:46:29Z'; sealed_utc=$now.ToString('yyyy-MM-ddTHH:mm:ssZ'); elapsed_assessment_wall_seconds=[math]::Round(($now-[datetime]::Parse('2026-09-21T00:44:57Z').ToUniversalTime()).TotalSeconds,1);
 evidence_method='READ of committed reports/reviews plus independent hand derivations; no REPLAY or INDEPENDENT EVALUATOR';
 mathematical_pilots=0; mathematical_computational_seconds=0; numerical_environment=$null;
 source_binding_file='results/a25_02/SOURCE_BINDINGS.json'; sources=(Get-Content -Raw "$out/SOURCE_BINDINGS.json" | ConvertFrom-Json).sources;
 artifacts=@($artifacts);
 exclusions=@('Manifest does not hash itself','No A25-01 or unfinished B25 scientific input','No mathematical evaluator or source-certificate replay','No git mutation, publication, shared-rule edit, agents or tool memory','No equation, actual-padding witness, positive gap or asymptotic bound produced');
 downstream_gate='G29: separately authorized delivery and independent review remain open';
 proposed_add_list='results/a25_02/ADD_LIST.txt'
}
if($manifest.elapsed_assessment_wall_seconds -gt 2700) { throw 'Assessment exceeded 45 minutes; correct report before sealing.' }
$manifest | ConvertTo-Json -Depth 12 | Set-Content -Encoding utf8NoBOM "$out/MANIFEST.json"
$reloaded=Get-Content -Raw "$out/MANIFEST.json" | ConvertFrom-Json
foreach($a in $reloaded.artifacts) {
 $actual=(Get-FileHash -Algorithm SHA256 -LiteralPath "$repo/$($a.path)").Hash.ToLowerInvariant()
 if($actual -ne $a.sha256) {throw "Seal mismatch $($a.path)"}
}
foreach($p in $all) {if(-not(Test-Path -LiteralPath "$repo/$p")){throw "Add list missing: $p"}}
"Verified $($artifacts.Count) payload hashes and $($all.Count) explicit add paths."
"Manifest SHA256: $((Get-FileHash -Algorithm SHA256 "$out/MANIFEST.json").Hash.ToLowerInvariant())"
"Elapsed wall seconds: $($manifest.elapsed_assessment_wall_seconds); pilots 0; mathematical seconds 0."
