"""Create provenance manifests, then deliver this session's committed bundle."""
import argparse
import datetime as dt
import hashlib
import json
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT/'results/b13_12'
BASE = '00495110c62acfbbbc951e82cc218ed091563b3f'
DEST = Path('C:/Users/swami/Projects/gct-gpt/Batch13_Results/B13-12')
INPUTS = [
    'docs/batch13_worker_preamble.md','docs/batch13_board.md','docs/batch13_corrections.md',
    'docs/stocktake_batch12.md','docs/brief_wording.md','docs/s78_report.md',
    'docs/s78_review.md','docs/rees_boundary_audit.md','docs/critic_rees_response.md',
    'docs/batch11_plan.md','docs/batch12_s1_s2_consolidated.md',
    'results/astra/S2/S2_report.md','results/astra/S2/REPLAY.md',
    'results/astra/S2/HANDOFF_s77.md','results/astra/S2/verify_s2.py',
    'results/astra/S2/build_chart_jobs.py','results/astra/S2/chart_manifest.json',
    'results/astra/S2/chart_coefficient_checks.json',
    'results/astra/S2/ker_coker_certificates.json',
    'results/astra/S2/intermediate_rank3_arc.json',
    'results/astra/S2/independent_jet_checks.json',
    'results/astra/S2/verification_summary.json',
    'results/astra/S2/cas/chart_0_Q.sing','results/astra/S2/cas/chart_64_Q.sing',
    'results/astra/S2/cas/reduced_dimS.sing',
    'results/s78_reduced_polys.json','analysis/wk12_s78_build_reduced.py',
    'analysis/wk12_s78_arc_control.py']


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT)


def digest(data):
    return dict(bytes=len(data), sha256=hashlib.sha256(data).hexdigest(),
                md5=hashlib.md5(data).hexdigest())


def save(path, obj):
    path.write_text(json.dumps(obj, indent=2) + '\n', encoding='utf-8')


def manifest():
    inputs=[]
    for name in INPUTS:
        data=(ROOT/name).read_bytes()
        blob=git('show',f'{BASE}:{name}')
        inputs.append(dict(path=name, worktree_bytes=digest(data),
                           base_git_blob_bytes=digest(blob)))
    save(OUT/'input_manifest.json',dict(board_numbering='batch13',session_id='B13-12',
         base=BASE, inputs=inputs,
         missing_inherited_artifacts=['results/astra/S2/tangent_calibration.json'],
         note='S2 tangent artifact regenerated by its verifier in the isolated output directory.'))
    artifacts = sorted(set([ROOT/'docs/b13_12_report.md', ROOT/'results/PREREG_b13_12.md'] +
                           list((ROOT/'analysis').glob('b13_12_*.py')) +
                           [p for p in OUT.rglob('*') if p.is_file() and p.name!='manifest.json'] +
                           [p for p in (ROOT/'results/logs').glob('b13_12_*') if p.is_file()]))
    entries=[]
    for p in artifacts:
        data=p.read_bytes()
        assert len(data)<5_000_000, p
        entries.append(dict(path=p.relative_to(ROOT).as_posix(), **digest(data)))
    save(OUT/'manifest.json',dict(board_numbering='batch13',session_id='B13-12',model='gpt-6-astra',
         reasoning_effort='xhigh',base=BASE,branch='b13-12',created_utc=dt.datetime.now(dt.timezone.utc).isoformat(),
         bundle_parts=1,part_names=['b13_12_five_variable_closure.part00'],
         evidence_status='Global formulation and universal-support theorem proved; finite controls certified; global elimination unrun.',
         coefficient_checks=69,triangular_checks=70,primes=[2147483647,2147483629],
         inherited_lmr=dict(det_rank_exact=273,padded_rank_floor=269,D='mult_pad-mult_det',
                            unconditional_formula='D=1-i_pad(24)',certified_interval=[-4,1]),
         workers=1,blas_threads=1,process_memory_cap_bytes=1024**3,
         dependencies=dict(python='bundled CPython 3.12',numpy='available; not used',
                           flint='unavailable',sympy='unavailable',scipy='unavailable',psutil='unavailable',
                           Singular='not found on PATH',msolve='not found on PATH',
                           installation_attempt='pip failed before download at network socket access WinError 10013',
                           actual_arithmetic='Python standard library, exact integers and Fraction'),
         hashes_are='Exact delivered worktree bytes. Git archives contain canonical Git bytes; see delivery manifest. This manifest excludes itself.',
         artifacts=entries))
    print(f'Hashed {len(inputs)} inputs and {len(entries)} artifacts.')


def deliver():
    assert git('branch','--show-current').decode().strip()=='b13-12'
    assert not git('status','--porcelain').strip(), 'Commit all session files before delivery.'
    head=git('rev-parse','HEAD').decode().strip()
    git('merge-base','--is-ancestor',BASE,head)
    manifest=json.loads((OUT/'manifest.json').read_text())
    for rec in manifest['artifacts']:
        assert digest((ROOT/rec['path']).read_bytes())['sha256']==rec['sha256'],rec['path']
    DEST.mkdir(parents=True,exist_ok=True)
    bundle=DEST/'b13_12_five_variable_closure.bundle'
    part=DEST/'b13_12_five_variable_closure.part00'
    archive=DEST/'b13_12_changed_files.zip'
    for p in (bundle,part,archive):
        if p.exists():
            raise RuntimeError(f'Delivery already exists: {p}; inspect before replacement.')
    git('bundle','create',str(bundle),f'{BASE}..HEAD')
    verify=subprocess.run(['git','bundle','verify',str(bundle)],cwd=ROOT,capture_output=True,text=True,check=True)
    (DEST/'bundle_verify.txt').write_text(verify.stdout+verify.stderr)
    heads=git('bundle','list-heads',str(bundle)).decode()
    assert head in heads
    (DEST/'bundle_heads.txt').write_text(heads)
    shutil.copyfile(bundle,part)
    assert bundle.read_bytes()==part.read_bytes()
    changed=git('diff','--name-only',BASE,head).decode().splitlines()
    assert all(p.startswith(('analysis/b13_12_','docs/b13_12_','results/b13_12/',
                             'results/PREREG_b13_12.md','results/logs/b13_12_')) for p in changed)
    for name in changed:
        assert len(git('show',f'{head}:{name}'))<5_000_000,name
    git('archive','--format=zip',f'--output={archive}',head,*changed)
    for name,source in [('b13_12_report.md',ROOT/'docs/b13_12_report.md'),
                        ('manifest.json',OUT/'manifest.json'),('input_manifest.json',OUT/'input_manifest.json'),
                        ('REPLAY.md',OUT/'REPLAY.md')]:
        shutil.copyfile(source,DEST/name)
    # Full direct copies preserve the exact bytes hashed in the artifact manifest.
    artifact_root=DEST/'artifacts'
    for name in changed:
        dest=artifact_root/name
        dest.parent.mkdir(parents=True,exist_ok=True)
        shutil.copyfile(ROOT/name,dest)
    for alg in ('md5','sha256'):
        lines=[f"{getattr(hashlib,alg)(p.read_bytes()).hexdigest()}  {p.name}" for p in (bundle,part,archive)]
        (DEST/f'b13_12_five_variable_closure.bundle.{alg}').write_text('\n'.join(lines)+'\n')
    delivery=dict(board_numbering='batch13',session_id='B13-12',model='gpt-6-astra',reasoning_effort='xhigh',
                  base=BASE,head=head,branch='b13-12',delivered_utc=dt.datetime.now(dt.timezone.utc).isoformat(),
                  bundle_parts=1,whole_file=bundle.name,parts=[part.name],part00_identical_to_whole=True,
                  history_rewritten=False,bundle_verified=True,changed_file_count=len(changed),
                  files=[dict(name=p.name,**digest(p.read_bytes())) for p in (bundle,part,archive)],
                  artifact_byte_copies='artifacts/ preserves worktree bytes used by manifest.json',
                  archive_semantics='Canonical committed Git bytes, directories retained; prerequisite base not included.',
                  math_status='Formulation repaired; universal rank-one support and triangular family proved; global containment remains open.')
    save(DEST/'delivery_manifest.json',delivery)
    print(json.dumps(delivery,indent=2))


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('mode',choices=['manifest','deliver'])
    args=parser.parse_args()
    {'manifest':manifest,'deliver':deliver}[args.mode]()
