#!/usr/bin/env python3
"""
B28-01a -- collect the host outputs into the worktree's results/b28_01/.

Files of at most 5,000,000 bytes are copied byte-for-byte; larger ones (the
calibration kernels K and the large cover arrays) stay on the host and are
bound by SHA-256 and size in HOST_RETAINED.json -- every one of them is
regenerated by the verifier from mathematical inputs.  The run log becomes
RESOURCE_RECEIPT.json with the frozen-code hashes as the input binding and
the per-run output file hashes.

usage: python3 b28_01_finalize.py HOSTROOT DEST
"""
import sys, os, json, hashlib, shutil

LIMIT = 5_000_000
host, dest = sys.argv[1:3]
assert not os.path.exists(dest), dest


def sha(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''): h.update(b)
    return h.hexdigest()


retained = []
def collect(src, dst):
    for dp, _, fs in os.walk(src):
        for fn in sorted(fs):
            s = os.path.join(dp, fn); rel = os.path.relpath(s, src)
            if os.path.getsize(s) <= LIMIT:
                d = os.path.join(dst, rel); os.makedirs(os.path.dirname(d), exist_ok=True); shutil.copyfile(s, d)
            else:
                retained.append(dict(host_path=os.path.relpath(s, host), bytes=os.path.getsize(s), sha256=sha(s)))

os.makedirs(dest)
collect(os.path.join(host, 'out'), dest)                                  # control/, cal1/, cal2/, rates, price
collect(os.path.join(host, 'runs'), os.path.join(dest, 'runs'))
collect(os.path.join(host, 'dev'), os.path.join(dest, 'dev_fixtures'))
collect(os.path.join(host, 'superseded_v1', 'out'), os.path.join(dest, 'superseded_v1', 'out'))
shutil.copyfile(os.path.join(host, 'superseded_v1', 'runlog_v1.jsonl'), os.path.join(dest, 'superseded_v1', 'runlog_v1.jsonl'))
for nm in ('frozen_v2_hashes.txt', 'engine_hashes.txt'):
    shutil.copyfile(os.path.join(host, nm), os.path.join(dest, nm))
fz = {}
for fn in sorted(os.listdir(os.path.join(host, 'frozen'))):
    fz[fn] = sha(os.path.join(host, 'frozen', fn))
v1 = {fn: sha(os.path.join(host, 'superseded_v1', 'frozen', fn)) for fn in sorted(os.listdir(os.path.join(host, 'superseded_v1', 'frozen')))}
json.dump(dict(schema='b28-01-host-retained/1', rule=f'files larger than {LIMIT} bytes are not committed; bound here by raw SHA-256',
               files=sorted(retained, key=lambda r: r['host_path'])), open(os.path.join(dest, 'HOST_RETAINED.json'), 'w'), indent=1)

# resource receipt
outdir = {'ctl': 'out/control', 'cal1': 'out/cal1', 'cal2': 'out/cal2'}
runs = [dict(json.loads(l), code='frozen v2') for l in open(os.path.join(host, 'runs', 'runlog.jsonl'))]
v1l = [l for l in open(os.path.join(host, 'superseded_v1', 'runlog_v1.jsonl'))]
for r in runs:
    if not r['label'].startswith('v2_'): r['code'] = 'frozen v1 (superseded: wall-clock durations; see report)'
for r in runs:
    key = r['label'].replace('v2_', '').split('_')[0]
    base = os.path.join(host, 'superseded_v1' if r['code'] != 'frozen v2' else '', outdir.get(key, 'out'))
    r['stdout_sha256'] = sha(os.path.join(host, 'runs', r['label'] + '.out'))
    r['stderr_log_sha256'] = sha(os.path.join(host, 'runs', r['label'] + '.log'))
outputs = {}
for k, d in outdir.items():
    p = os.path.join(host, d)
    outputs[d] = {os.path.relpath(os.path.join(dp, f), p): sha(os.path.join(dp, f)) for dp, _, fs in os.walk(p) for f in sorted(fs)}
json.dump(dict(schema='b28-01-resource-receipt/1',
               enforcement='systemd-run --user --scope -p MemoryMax=8G -p MemorySwapMax=0 (8 GiB) + GNU timeout + GNU time -v; OPENBLAS/OMP/MKL/NUMEXPR threads = 1; one process at a time',
               frozen_code_v2_sha256=fz, frozen_code_v1_sha256_superseded=v1, runs=runs, output_sha256=outputs),
          open(os.path.join(dest, 'RESOURCE_RECEIPT.json'), 'w'), indent=1)
print('retained', len(retained), sum(r['bytes'] for r in retained))
