#!/usr/bin/env python3
"""Session 27 -- by-product: the degree of the determinantal hypersurface.

D_4^{det_4} has codimension 1 in Sym^4 C^4 (Jacobian rank 34 of 35), so its
ideal is principal, generated by an irreducible GL_4-semi-invariant F.  A
semi-invariant on Sym^4 C^4 of degree e has weight det^e, i.e. sits at
lam = (e,e,e,e).  So e is the least delta with mult_det((delta^4), delta) < a.
"""
import sys, time
sys.path.insert(0, '/root/gct/analysis')
from wk7_s27_rank import measure, det_form, per_padded, monomials
from wk7_s27_pleth import a_of

f4, N4 = det_form(4); fp, Np = per_padded(3)
print("delta  lam        |basis|   a   mult_det   mult_pad")
for d in range(2, 8):
    lam = (d, d, d, d)
    nb = len(monomials(4, 4, d, lam))
    if nb > 20000:
        print("  %2d   %-10s %7d   (skipped, too large)" % (d, str(lam), nb)); continue
    t0 = time.time()
    md = measure(f4, N4, 4, 4, d, lam)
    mp = measure(fp, Np, 4, 4, d, lam, seed=29)
    for m in (md, mp):
        if m['a']: assert m['mult'] == m['mult_p2'], (d, m)
    print("  %2d   %-10s %7d %3d      %2d %-9s %2d %s   [%.0fs]"
          % (d, str(lam), nb, md['a'], md['mult'],
             "(<a)" if md['mult'] < md['a'] else "(=a)", mp['mult'],
             "(<a)" if mp['mult'] < mp['a'] else "(=a)", time.time() - t0))
    sys.stdout.flush()
