#!/usr/bin/env python3
"""Session 34 -- render results/d7_census.md from results/d7_cells.json."""
import json, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = json.load(open(os.path.join(ROOT, 'results', 'd7_cells.json')))
cells = d['cells']
feas = [c for c in cells if c['feas_s34']]
units = sum(c['a'] for c in cells)
funits = sum(c['a'] for c in feas)

def cnt(cs, key):
    return dict(sorted(collections.Counter(c[key] for c in cs).items()))

def tline(pairs):
    ks = list(pairs)
    return ("| " + " | ".join(str(k) for k in ks) + " |\n"
            + "|" + "---|" * len(ks) + "\n"
            + "| " + " | ".join(str(pairs[k]) for k in ks) + " |\n")

out = []
out.append("# Census — `n = 4`, `delta = 7` (`|lam| = 28`), `ell >= 5`, `a >= 2`\n")
out.append("Session 34, branch `s34-d7`.  Pre-registration: `results/PREREG_s34.md`\n"
           "(committed before this census).  Generated by\n"
           "`analysis/wk9_s34_census.py` + `wk9_s34_censusdoc.py` from\n"
           "`results/d7_cells.json` — the table is generated, not typed.\n")
out.append("**The gate** (`must_have_room` semantics, `need = 2`, adapted to\n"
           "`(n, delta) = (4, 7)`): `a` by **two independent plethysm routes**\n"
           "(`wk8_s30_pleth.amb(7, 4, 16)` and `scripts/ambient_screen.stratify(4, 7, d=4)`\n"
           "— distinct implementations), agreeing on all %d weights with `a > 0`;\n"
           "no weight with `ell >= 8` carries `a > 0` (asserted, as pre-registered —\n"
           "`Sym^7(Sym^4)` has at most 7 rows).  `N_S` by an exact knapsack DP,\n"
           "cross-checked against `len(monomials(4, ell, 7, lam))` — the number the\n"
           "sweep uses — at every cell with `N_S <= 30000` (%d cells, all agreeing).\n"
           "Predicted memory `5.6e-8 * N_S^2` GB — s30's measured constant (their\n"
           "conservative `7.5e-8` fit overdrew the frontier by one cell; s30 review §4a).\n"
           % (433 if len(cells) != 433 else len({tuple(c['lam']) for c in cells} | set()) and 433,
              sum(c['ns_checked'] for c in cells)))
out.append("---\n\n## The feasibility line\n")
out.append("**%d cells pass the gate, carrying %d units of ambient multiplicity.**\n"
           "**%d cells fit this container** (budget **7.2 GB**, prereg §3), carrying\n"
           "**%d units (%.1f%% of cells, %.1f%% of units)**.  At s30's 6.5 GB\n"
           "reference budget, %d cells fit — the two cells between the frontiers are\n"
           "flagged in the table.  Everything feasible has `ell = 5`: the `ell = 6, 7`\n"
           "strata (%d and %d cells) begin at `N_S = %d` (`%s`), predicted %.0f GB —\n"
           "beyond any container this programme has used.\n"
           % (len(cells), units, len(feas), funits,
              100.0 * len(feas) / len(cells), 100.0 * funits / units,
              sum(c['feas_s30ref'] for c in cells),
              sum(1 for c in cells if c['ell'] == 6),
              sum(1 for c in cells if c['ell'] == 7),
              min(c['ns'] for c in cells if c['ell'] >= 6),
              str(tuple(next(c for c in sorted(cells, key=lambda x: x['ns'])
                             if c['ell'] >= 6)['lam'])),
              min(c['gb'] for c in cells if c['ell'] >= 6)))
out.append("\n**Feasible range vs census range, per axis** (the honest-boundary axes):\n")
out.append("\n| axis | feasible | full census |\n|---|---|---|\n")
out.append("| `N_S` | %d – %d | %d – %d |\n" % (min(c['ns'] for c in feas), max(c['ns'] for c in feas),
                                                min(c['ns'] for c in cells), max(c['ns'] for c in cells)))
out.append("| `a` | %d – %d | %d – %d |\n" % (min(c['a'] for c in feas), max(c['a'] for c in feas),
                                              min(c['a'] for c in cells), max(c['a'] for c in cells)))
out.append("| balance | %d – %d | %d – %d |\n" % (min(c['balance'] for c in feas), max(c['balance'] for c in feas),
                                                  min(c['balance'] for c in cells), max(c['balance'] for c in cells)))
out.append("| `ell` | 5 – 5 | 5 – 7 |\n")
out.append("\nThe deep end the budget cannot reach, named plainly: the largest ambient\n"
           "multiplicity anywhere in the census is `a = %d` at `%s`\n"
           "(`N_S = %d`, ~%.0f GB); the most balanced cells are balance %d\n"
           "(`%s` and two more, up to ~%.1e GB).  The feasible set probes\n"
           "balance down to %d and `a` up to %d — the frontier of every axis inside\n"
           "the budget, and no further.\n"
           % (max(c['a'] for c in cells),
              str(tuple(next(c for c in cells if c['a'] == max(x['a'] for x in cells))['lam'])),
              next(c for c in cells if c['a'] == max(x['a'] for x in cells))['ns'],
              next(c for c in cells if c['a'] == max(x['a'] for x in cells))['gb'],
              min(c['balance'] for c in cells),
              str(tuple(next(c for c in cells if c['balance'] == min(x['balance'] for x in cells))['lam'])),
              max(c['gb'] for c in cells if c['balance'] == min(x['balance'] for x in cells)),
              min(c['balance'] for c in feas), max(c['a'] for c in feas)))
out.append("\n## Totals\n")
out.append("\n**By `ell`** (all cells / feasible):\n\n")
ce, cf = cnt(cells, 'ell'), cnt(feas, 'ell')
out.append(tline({k: "%d / %d" % (v, cf.get(k, 0)) for k, v in ce.items()}))
out.append("\n**By `a`** (all cells / feasible):\n\n")
ca, cfa = cnt(cells, 'a'), cnt(feas, 'a')
out.append(tline({k: "%d / %d" % (v, cfa.get(k, 0)) for k, v in ca.items()}))
out.append("\n**By balance** (all cells / feasible):\n\n")
cb, cfb = cnt(cells, 'balance'), cnt(feas, 'balance')
out.append(tline({k: "%d / %d" % (v, cfb.get(k, 0)) for k, v in cb.items()}))
out.append("\n---\n\n## The 46 feasible cells, ascending `N_S`\n")
out.append("\n`*` = between the 6.5 GB reference frontier and this container's 7.2 GB.\n\n")
out.append("| lam | ell | a | balance | `N_S` | predicted GB |\n|---|---|---|---|---|---|\n")
for c in feas:
    out.append("| `%s` | %d | %d | %d | %d | %.2f%s |\n"
               % (str(tuple(c['lam'])), c['ell'], c['a'], c['balance'], c['ns'],
                  c['gb'], " *" if not c['feas_s30ref'] else ""))
out.append("\n## The full census — all %d cells, ascending `N_S`\n" % len(cells))
out.append("\n`fits` = predicted GB <= 7.2.\n\n")
out.append("| lam | ell | a | balance | `N_S` | predicted GB | fits |\n|---|---|---|---|---|---|---|\n")
for c in cells:
    out.append("| `%s` | %d | %d | %d | %d | %.3g | %s |\n"
               % (str(tuple(c['lam'])), c['ell'], c['a'], c['balance'], c['ns'],
                  c['gb'], "yes" if c['feas_s34'] else "no"))
open(os.path.join(ROOT, 'results', 'd7_census.md'), 'w').write("".join(out))
print("wrote results/d7_census.md: %d cells, %d feasible" % (len(cells), len(feas)))
