#!/usr/bin/env python3
"""
Session 43 -- the coverage arithmetic, redone from the census and the three
ledgers (s36, s41, s43).  Writes results/s43_coverage.md.

Everything here is re-derived; nothing is copied from results/s41_coverage.md.

usage: python3 wk9_s43_report.py [--frontier 20000]
"""
import sys, os, json

HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
ROOT = os.path.abspath(os.path.join(HERE, '..'))
from wk9_s43_todo import cells_of, ledger_cells, S41LED, S36LED, S36AONE

S43LED = os.path.join(ROOT, 'results', 's43_ledger.md')


def rows_of(path, prefixes=('| 7 ', '| 8 ', '| 9 ')):
    """(lam, delta) -> dict of the measured columns, for s41/s43 ledger format"""
    out = {}
    for ln in open(path):
        if ln[:4] in prefixes:
            c = [x.strip() for x in ln.strip().strip('|').split('|')]
            lam = tuple(int(x) for x in c[1].strip('`').strip('()').split(','))
            out[(lam, int(c[0]))] = dict(a=int(c[2]), m_det=int(c[3]), n_chi=int(c[6]),
                                         mult_det=int(c[9]), mult_pad=int(c[10]),
                                         mult_red=int(c[11]), D=int(c[12]))
    return out


def main():
    frontier = int(sys.argv[sys.argv.index('--frontier') + 1]) if '--frontier' in sys.argv else 20000
    cen = cells_of()
    s41 = rows_of(S41LED)
    s43 = rows_of(S43LED) if os.path.exists(S43LED) else {}
    s36 = ledger_cells(S36LED) | ledger_cells(S36AONE)

    L = ["# Session 43 — six-row coverage, re-derived\n",
         "Generated by `analysis/wk9_s43_report.py` from `results/sixrow_census.md`, `results/s36_ledger.md`, "
         "`results/s36_aone.md`, `results/s41_ledger.md` and `results/s43_ledger.md`.  Nothing is copied from "
         "`results/s41_coverage.md`; the counts below are rebuilt from the census table itself.\n",
         "## Coverage (fractions of what exists; `λ_1 ≥ δ`, `a ≥ 1`, `ℓ = 6`)\n",
         "| δ | eligible cells | units | fit at 20000 | units | measured s36+s41 | new s43 | **measured now** | units | "
         "**still unmeasured in reach** | `mult_det < a` | `mult_pad < a` | `mult_pad < mult_red` |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    tot = dict(cells=0, units=0, reach=0, meas=0, meas_u=0, new=0, left=0)
    bites, dets, perm = [], [], []
    for d in (7, 8):
        cells = cen[d]
        reach = [x for x in cells if x['approx'] == '' and x['n_chi'] <= frontier]
        old = [x for x in reach if bool(x['s36']) or (x['lam'], d) in s41]
        new = [x for x in reach if (x['lam'], d) in s43]
        meas = [x for x in reach if x in old or x in new]
        left = [x for x in reach if x not in meas]
        nd = sum(1 for k, v in list(s41.items()) + list(s43.items()) if k[1] == d and v['mult_det'] < v['a'])
        np_ = sum(1 for k, v in list(s41.items()) + list(s43.items()) if k[1] == d and v['mult_pad'] < v['a'])
        npr = sum(1 for k, v in list(s41.items()) + list(s43.items()) if k[1] == d and v['mult_pad'] < v['mult_red'])
        L.append(f"| {d} | {len(cells)} | {sum(x['a'] for x in cells)} | {len(reach)} | "
                 f"{sum(x['a'] for x in reach)} | {len(old)} | {len(new)} | **{len(meas)}** "
                 f"({100*len(meas)//len(cells)}%) | {sum(x['a'] for x in meas)} | **{len(left)}** | "
                 f"{nd} | {np_} | {npr} |")
        tot['cells'] += len(cells); tot['units'] += sum(x['a'] for x in cells)
        tot['reach'] += len(reach); tot['meas'] += len(meas)
        tot['meas_u'] += sum(x['a'] for x in meas); tot['new'] += len(new); tot['left'] += len(left)
    L.append("")
    L.append(f"**Reachable set at `n_χ ≤ {frontier}`: {tot['reach']} cells; measured now {tot['meas']} "
             f"({tot['meas_u']} units), of which {tot['new']} new this session; still unmeasured in reach "
             f"{tot['left']}.**\n")

    # by a and by balance, delta by delta
    for d in (7, 8):
        cells = cen[d]
        reach = [x for x in cells if x['approx'] == '' and x['n_chi'] <= frontier]
        meas = set(x['lam'] for x in reach
                   if bool(x['s36']) or (x['lam'], d) in s41 or (x['lam'], d) in s43)
        for keyname, keyf in (('a', lambda x: x['a']), ('balance', lambda x: x['bal'])):
            tab = {}
            for x in cells:
                k = keyf(x)
                t, m = tab.get(k, (0, 0))
                tab[k] = (t + 1, m + (1 if x['lam'] in meas else 0))
            L.append(f"`δ = {d}` measured/total by {keyname}: "
                     + ", ".join(f"`{keyname[0]}={k}`: {v[1]}/{v[0]}" for k, v in sorted(tab.items()))
                     + ".\n")

    # det side / pad side
    allrows = {**s41, **s43}
    det_bites = [(k, v) for k, v in allrows.items() if v['mult_det'] < v['a']]
    pad_bites = sorted([(k, v) for k, v in allrows.items() if v['mult_pad'] < v['a']],
                       key=lambda kv: (kv[0][1], kv[0][0]))
    L.append("## Det side\n")
    if det_bites:
        L.append("**Cells with `mult_det < a`:** " + ", ".join(f"`{k[0]}` δ={k[1]} (a={v['a']}, "
                 f"mult_det={v['mult_det']})" for k, v in det_bites) + "\n")
    else:
        L.append(f"No measured `ℓ = 6` cell has `mult_det < a`, in {len(allrows)} rows of the s41 and s43 "
                 "ledgers (and none in the s36 record either).  The determinant's six-row ideal is empty at "
                 "every reachable weight of `δ = 6, 7, 8` that has ever been measured.\n")
    L.append("## Pad side\n")
    L.append("Cells with `mult_pad < a` in the s41 + s43 ledgers: "
             + (", ".join(f"`{k[0]}` δ={k[1]} (a={v['a']}, mult_pad={v['mult_pad']}, mult_red={v['mult_red']})"
                          for k, v in pad_bites) if pad_bites else "none") + ".\n")
    L.append("Cells with `mult_pad < mult_red` (permanent-specific equations): "
             + (", ".join(f"`{k[0]}` δ={k[1]}" for k, v in allrows.items()
                          if v['mult_pad'] < v['mult_red']) or "none") + ".\n")
    L.append("## Pieri transport (Prop. 8(1))\n")
    L.append("`I(D_6^{per_3})_7 = 0` is now measured at **all 27** length-6 weights `μ ⊢ 21` with `a ≥ 1` "
             "(`results/s41_per6.md` 20, `results/s43_per6.md` 7).  By Prop. 8(1) of `docs/transfer_lemma.md` "
             "this makes `mult_pad = mult_red` a **theorem at every weight of degree 7**, with no points in it "
             "— the cell-by-cell Pieri-transport bookkeeping of `results/s41_coverage.md` is no longer needed "
             "at `δ = 7`, and its one \"not forced\" cell `(15,4,4,2,2,1)` is forced.\n")
    open(os.path.join(ROOT, 'results', 's43_coverage.md'), 'w').write("\n".join(L))
    print(json.dumps(tot, indent=1))
    print("wrote results/s43_coverage.md")


if __name__ == '__main__':
    main()
