#!/usr/bin/env python3
"""
Session 46 -- the isotypic reduction by GENERATORS instead of group elements.

Why this module exists.  Session 45's memory-lean build (wk9_s45_build) removed
the determinant-side memory wall but left one step scaling with |Stab_W(lam)|:
_canon_acc makes 2|Stab| passes over the (N_S x delta) monomial array, each pass
a gather, a row sort, a combinadic code and a searchsorted.  At the named target
(8,4,4,4,4,4)_7 -- N_S = 10,060,304, |Stab| = 120 -- that is 240 such passes and
it did not finish inside session 45's build budget.

Stab_W(lam) = prod_B S_{k_B} is a Young subgroup, GENERATED by the adjacent
transpositions inside its blocks: 4 of them at |Stab| = 120, not 120.  So:

  * compute the image-index permutation ONCE PER GENERATOR (#gen passes, not
    2|Stab|).  Each generator is a transposition, hence an involution, so its
    permutation array is an involution and the generator edges form a matching;
  * build the orbit partition by min-label propagation over those edges,
    iterated to a fixed point (canon[j] = min index in the orbit of j);
  * carry the character along the same edges: if g.m_j = m_{j'} then a
    transporter for j' composed with g is a transporter for j, so
    s[j] = chi(g) * s[j'].  Anchored at s[representative] = +1;
  * drop an orbit exactly when some generator edge inside it is sign-inconsistent.

The last item is s45's `acc[j] = 0` test reached more cheaply, and it is the
same test: a sign conflict on a closed walk from the representative is exactly
an element h of Stab_rep with chi(h) = -1, which is exactly
sum_{h in Stab_rep} chi(h) = 0, which is exactly acc[rep] = 0.

Cost O(N_S * #gen * rounds) with `rounds` the generator-graph diameter of one
orbit (<= |Stab|; ~5-10 in practice), against O(N_S * |Stab|).

WHAT IS IDENTICAL to wk9_s45_build, by construction and checked in
analysis/wk9_s46_validate.py (V4):

  * the monomial array and its order (monomials_array is imported, not copied),
  * the multiset combinadic code (_codes, imported),
  * the orbit partition, the representative (minimum index), the per-monomial
    sign, the dropped-orbit set, n_chi and col_of,
  * the raising rule, the H-orbit dedup of target rows, the chi-obstructed
    cancellation assertion, and hence E's row count, nnz and row space,
  * the evaluation rows (ev_rows_arr is imported, not copied).

The ONLY textual difference from wk9_s45_build.raising_rows_arr is the two
lines that build the common stabiliser H: generators instead of the full group.
"""
import sys, os, time
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from wk8_s30_core import exps
from wk9_s36_stabred import blocks_of, perm_tables
from wk9_s42_orbits import _codes
from wk9_s45_build import monomials_array, ev_rows_arr, log, _rss_gb

# ------------------------------------------------------------- generators
def stab_generators(lam, fix=()):
    """[(perm tuple on range(r), chi_lam(perm))] for a generating set of the
    Young subgroup Stab_W(lam) (or of H = Stab_W(lam) cap {fixes `fix`
    pointwise}): the adjacent transpositions of the movable indices of each
    block.  chi_lam(transposition inside a block of value m) = (-1)^m, from the
    lemma of docs/stabiliser_reduction.md section 1."""
    r = len(lam)
    out = []
    for B in blocks_of(lam):
        m = lam[B[0]]
        if m == 0: continue
        mov = [b for b in B if b not in fix]
        ch = -1 if m % 2 else 1
        for a, b in zip(mov, mov[1:]):
            p = list(range(r)); p[a] = b; p[b] = a
            out.append((tuple(p), ch))
    return out

def group_order(lam, fix=()):
    """|Stab_W(lam)| (restricted to elements fixing `fix`), without enumerating it."""
    from math import factorial
    o = 1
    for B in blocks_of(lam):
        if lam[B[0]] == 0: continue
        o *= factorial(len([b for b in B if b not in fix]))
    return o

# ------------------------------------------------------------- image index
def _image_index32(M, tab, sorted_codes, order, L):
    """index in the basis of g.m for every monomial m, as int32.  Same value as
    wk9_s45_build._image_index; one fewer full copy of the (N x delta) array
    (the row sort is done in place)."""
    img = np.asarray(tab, dtype=np.int32)[M]
    img.sort(axis=1)
    c = _codes(img, L)
    del img
    p = np.searchsorted(sorted_codes, c)
    assert p.max(initial=0) < len(sorted_codes) and np.all(sorted_codes[p] == c), \
        "image monomial not in the basis (weight not preserved?)"
    del c
    return order[p].astype(np.int32)

# ------------------------------------------------ orbits and signs by walk
def canon_sign_gen(M, gtabs, L, verbose=False):
    """(canon, sgn, obstructed, rounds) with

        canon[j]      = the minimum index in the Stab-orbit of monomial j,
        sgn[j]        = chi(u) for any u in Stab with u . m_{canon[j]} = m_j,
                        or 0 if the orbit is dropped,
        obstructed[j] = True iff the orbit of j is dropped (equivalently, iff
                        some h in Stab fixes m_j with chi(h) = -1).

    Matches wk9_s45_build._canon_acc's (canon, sign(acc), acc == 0) exactly,
    including the anchor sgn[representative] = +1."""
    N = M.shape[0]
    codes0 = _codes(M, L)
    order = np.argsort(codes0, kind='stable')
    sorted_codes = codes0[order]
    assert np.all(np.diff(sorted_codes) > 0), "codes not injective"
    del codes0
    perms, chs = [], []
    for tab, ch in gtabs:
        perms.append(_image_index32(M, tab, sorted_codes, order, L)); chs.append(ch)
    del sorted_codes, order
    canon = np.arange(N, dtype=np.int32)
    s = np.ones(N, dtype=np.int8)
    rounds = 0
    while True:
        changed = False
        for perm, ch in zip(perms, chs):
            pc = canon[perm]
            better = pc < canon
            if better.any():
                ps = s[perm]
                if ch == -1: ps = -ps
                canon[better] = pc[better]
                s[better] = ps[better]
                changed = True
                del ps
            del pc, better
        rounds += 1
        if not changed: break
        if rounds > 4 * N + 8:
            raise RuntimeError("label propagation did not converge")
    # the fixed point is constant on orbits and equal to the minimum index:
    # no generator edge can lower a label, and each generator is an involution
    for perm in perms:
        assert np.array_equal(canon[perm], canon), "orbit labels not constant on an edge"
    # consistency of the sign, edge by edge; a conflict anywhere drops the orbit
    bad = np.zeros(N, dtype=bool)
    for perm, ch in zip(perms, chs):
        cand = s[perm] if ch == 1 else -s[perm]
        np.logical_or(bad, cand != s, out=bad)
        del cand
    del perms
    obstructed = np.zeros(N, dtype=bool)
    if bad.any():
        conflict_root = np.zeros(N, dtype=bool)
        conflict_root[canon[bad]] = True
        obstructed = conflict_root[canon]
        del conflict_root
    del bad
    sgn = s.astype(np.int64)
    sgn[obstructed] = 0
    del s
    return canon, sgn, obstructed, rounds

# ------------------------------------------------------ isotypic reduction
def orbit_setup_gen(n, r, delta, lam, M=None, verbose=True):
    """The chi_lam-isotypic reduction by generators.  Same dict contract as
    wk9_s45_build.orbit_setup_arr: dict(M, col_of, sgn, n_chi, N_S, stab,
    dropped, secs)."""
    lam = tuple(lam) + (0,) * (r - len(lam))
    t0 = time.time()
    L = len(exps(n, r))
    gens = stab_generators(lam)
    gtabs = perm_tables(n, r, gens)
    G = group_order(lam)
    if M is None:
        M = monomials_array(n, r, delta, lam, verbose=verbose)
    N = M.shape[0]
    if N == 0:
        return dict(M=M, col_of=np.zeros(0, np.int64), sgn=np.zeros(0, np.int64),
                    n_chi=0, N_S=0, stab=G, dropped=0, secs=0.0, rounds=0, ngen=len(gens))
    canon, sgn, obstructed, rounds = canon_sign_gen(M, gtabs, L, verbose=verbose)
    ar = np.arange(N, dtype=np.int32)
    is_rep = canon == ar
    kept = is_rep & ~obstructed
    n_chi = int(kept.sum())
    dropped = int(is_rep.sum()) - n_chi
    orbnum = np.full(N, -1, dtype=np.int64)
    orbnum[kept] = np.arange(n_chi, dtype=np.int64)
    col_of = orbnum[canon]
    del orbnum, is_rep, ar
    # the s45/s42 assertions, in the form the generator route can check them:
    # |Stab_rep| = |Stab| / |orbit| is an integer on every orbit, the twisted
    # sum vanishes on EVERY member of a dropped orbit (sgn = 0 there by
    # construction), and no kept monomial has sign 0.
    sizes = np.bincount(canon.astype(np.int64), minlength=N)
    live = col_of >= 0
    assert np.all(G % np.maximum(sizes[canon[live]], 1) == 0), \
        ("orbit size does not divide |Stab|", lam)
    assert np.all(sgn[live] != 0) and not sgn[~live].any(), \
        ("sign convention broken", lam)
    assert np.all(sizes[canon[live]] <= G), ("orbit larger than the group", lam)
    del canon, sizes, live, kept, obstructed
    if verbose:
        log(f"  lam={lam}: N_S={N} |Stab|={G} ngen={len(gens)} rounds={rounds} "
            f"n_chi={n_chi} (orbits dropped: {dropped}) "
            f"[gen, {time.time()-t0:.0f}s, HWM {_rss_gb():.2f} GB]")
    return dict(M=M, col_of=col_of, sgn=sgn, n_chi=n_chi, N_S=N, stab=G,
                dropped=dropped, secs=time.time() - t0, rounds=rounds, ngen=len(gens))

# ---------------------------------------------------- raising operators
def raising_rows_gen(n, r, delta, lam, arr, chunk=400000, cap=6_000_000, verbose=True):
    """wk9_s45_build.raising_rows_arr with the ONE change of this session: the
    common stabiliser H of the target rows is handled by its generators
    (canon_sign_gen) instead of by enumerating |H| group elements.  Everything
    else -- the raising rule, the chunked assembly, the H-orbit dedup, the
    chi-obstructed cancellation assertion and the row filtering -- is the same
    code path, and V4 checks the resulting E against wk9_s45_build's."""
    from scipy import sparse
    lam = tuple(lam) + (0,) * (r - len(lam))
    t0 = time.time()
    A = exps(n, r); idx = {a: k for k, a in enumerate(A)}; L = len(A)
    Aarr = np.array(A, dtype=np.int32)
    M = arr['M']; col_of = arr['col_of']; sgn = arr['sgn']; n_chi = arr['n_chi']
    N, d = M.shape
    blocks = []
    nfixed = 0
    for i in range(r - 1):
        j = i + 1
        if lam[j] == 0: continue
        tgt = tuple(lam[k] + (1 if k == i else (-1 if k == j else 0)) for k in range(r))
        T = monomials_array(n, r, delta, tgt)
        nt = T.shape[0]
        if nt == 0: continue
        codesT = _codes(T, L)
        orderT = np.argsort(codesT, kind='stable')
        sortedT = codesT[orderT]
        assert np.all(np.diff(sortedT) > 0)
        del codesT
        # --- the one change: generators of H, not the |H| elements of H ---
        Hgens = stab_generators(lam, fix=(i, j))
        Htabs = perm_tables(n, r, Hgens)
        nH = group_order(lam, fix=(i, j))
        canonT, _sgnT, obstructedT, _rT = canon_sign_gen(T, Htabs, L)
        # ------------------------------------------------------------------
        arT = np.arange(nt, dtype=np.int32)
        keepT = (canonT == arT) & ~obstructedT
        useT = keepT | obstructedT
        nrow = int(useT.sum())
        rowid = np.full(nt, -1, dtype=np.int64)
        rowid[useT] = np.arange(nrow, dtype=np.int64)
        obst_row = np.zeros(nrow, dtype=bool)
        obst_row[rowid[obstructedT]] = True
        del canonT, arT, _sgnT
        shift = np.full(L, -1, dtype=np.int64)
        for a, al in enumerate(A):
            if al[j] > 0:
                nb = list(al); nb[j] -= 1; nb[i] += 1; shift[a] = idx[tuple(nb)]
        acc_r, acc_c, acc_v = [], [], []
        pend = [0]
        hit = np.zeros(nt, dtype=bool)
        Ei = sparse.csr_matrix((nrow, n_chi), dtype=np.int64)

        def consolidate():
            nonlocal Ei, acc_r, acc_c, acc_v, pend
            if not acc_r: return
            rr = np.concatenate(acc_r); cc = np.concatenate(acc_c); vv = np.concatenate(acc_v)
            acc_r, acc_c, acc_v = [], [], []; pend[0] = 0
            X = sparse.coo_matrix((vv, (rr, cc)), shape=(nrow, n_chi), dtype=np.int64).tocsr()
            del rr, cc, vv
            X.sum_duplicates()
            Ei = (Ei + X).tocsr()
            del X

        for k in range(d):
            for b0 in range(0, N, chunk):
                b1 = min(b0 + chunk, N)
                colc = col_of[b0:b1]
                src = M[b0:b1, k]
                new = shift[src]
                valid = (new >= 0) & (colc >= 0)
                if not valid.any(): continue
                rows_new = M[b0:b1][valid].copy()
                rows_new[:, k] = new[valid]
                rows_new.sort(axis=1)
                c = _codes(rows_new, L); del rows_new
                p = np.searchsorted(sortedT, c)
                assert p.max(initial=0) < nt and np.all(sortedT[p] == c), \
                    "raising image not in the target basis"
                t = orderT[p]; del c, p
                hit[t] = True
                rid = rowid[t]; del t
                sel = rid >= 0
                if not sel.any(): continue
                coef = sgn[b0:b1][valid] * (Aarr[src[valid], i].astype(np.int64) + 1)
                acc_r.append(rid[sel]); acc_c.append(colc[valid][sel]); acc_v.append(coef[sel])
                pend[0] += int(sel.sum())
                del rid, sel, coef, valid, new, src, colc
                if pend[0] > cap: consolidate()
        consolidate()
        Ei.eliminate_zeros()
        if obst_row.any():
            sub = Ei[np.nonzero(obst_row)[0]]
            assert sub.nnz == 0, ("chi-obstructed fixed rows failed to cancel", lam, i, int(sub.nnz))
            del sub
        nfixed += int((obstructedT & hit).sum())
        Ek = Ei[np.nonzero(~obst_row)[0]]
        del Ei
        Ek.eliminate_zeros()
        nz = np.diff(Ek.indptr) > 0
        Ek = Ek[np.nonzero(nz)[0]]
        blocks.append(Ek)
        if verbose:
            log(f"    E_{i}{j}: |H|={nH} gens={len(Hgens)} targets {nt} canonical rows {Ek.shape[0]} "
                f"nnz {Ek.nnz} (obstructed fixed targets cancelled: {int((obstructedT & hit).sum())}) "
                f"[{time.time()-t0:.0f}s, HWM {_rss_gb():.2f} GB]")
        del T, sortedT, orderT, rowid, obst_row, keepT, obstructedT, useT, hit
    from scipy import sparse as _sp
    E = _sp.vstack(blocks).tocsr() if blocks else _sp.csr_matrix((0, n_chi), dtype=np.int64)
    E.sort_indices()
    return E, nfixed

# --------------------------------------------------------------- the cell
def build_cell_gen(lam, delta, n=4, verbose=True):
    """Drop-in for wk9_s45_build.build_cell, with the generator reduction."""
    lam = tuple(lam); r = len(lam)
    assert sum(lam) == n * delta and all(lam[i] >= lam[i + 1] for i in range(r - 1)) and lam[-1] > 0
    t0 = time.time(); t_m = time.time()
    M = monomials_array(n, r, delta, lam, verbose=verbose)
    mono_secs = time.time() - t_m
    arr = orbit_setup_gen(n, r, delta, lam, M=M, verbose=verbose)
    t_e = time.time()
    E, nfx = raising_rows_gen(n, r, delta, lam, arr, verbose=verbose)
    rows_secs = time.time() - t_e
    out = dict(lam=lam, delta=delta, r=r, arr=arr, E=E, N_S=arr['N_S'], stab=arr['stab'],
               n_chi=arr['n_chi'], nrows=int(E.shape[0]), nnz=int(E.nnz), nfixed=nfx,
               mono_secs=mono_secs, orbit_secs=arr['secs'], rows_secs=rows_secs,
               build_secs=time.time() - t0, hwm_gb=_rss_gb(),
               ngen=arr.get('ngen'), rounds=arr.get('rounds'))
    if verbose:
        log(f"  built[gen] {lam} d{delta}: N_S={out['N_S']} |Stab|={out['stab']} n_chi={out['n_chi']} "
            f"rows={out['nrows']} nnz={out['nnz']} ({out['build_secs']:.0f}s: mono {mono_secs:.0f}s "
            f"orbits {arr['secs']:.0f}s rows {rows_secs:.0f}s; HWM {out['hwm_gb']:.2f} GB)")
    return out
