-- Session 61: the dual variety of the 3x3 permanent hypersurface by implicitisation.
-- Z = closure { padj(A) : per_3(A) = 0 }, padj(A)_ij = 2x2 permanent complementary to (i,j)
-- (= d per_3 / d a_ij).  Eliminate the nine a_ij from (per_3(A), b_ij - padj(A)_ij); since
-- padj is homogeneous the image of the affine cone is the affine cone over Z, so the
-- elimination ideal in the b's is principal, generated by the equation of Z.  Its degree
-- is an independent confirmation of delta_7(per_3) (PREREG_s61.md M6).
--
-- usage: M2 --script analysis/wk9_s61_dual.m2 <prime>
p = if #scriptCommandLine > 1 then value scriptCommandLine#1 else 32003;
kk = if p == 0 then QQ else ZZ/p;
-- elimination order: a's first (to be eliminated), then b's
R = kk[a_0..a_8, b_0..b_8, MonomialOrder => Eliminate 9];
A = genericMatrix(R, a_0, 3, 3);
per3 = sum apply(permutations 3, s -> product apply(3, i -> A_(i, s#i)));
padj = apply(9, i -> diff(a_i, per3));
I = ideal(per3) + ideal apply(9, i -> b_i - padj#i);
tm = cpuTime();
G = selectInSubring(1, gens gb I);
stderr << "elimination done in " << floor(cpuTime() - tm) << " s" << endl;
Zid = ideal G;
print("number of generators of the elimination ideal: " | toString numgens Zid);
S = kk[b_0..b_8];
Zs = sub(Zid, S);
print("DEGREES " | toString apply(flatten entries gens Zs, f -> first degree f));
f = (flatten entries gens Zs)#0;
print("DIM/DEGREE of Z: dim = " | toString dim Zs | " (affine cone), degree = " | toString degree Zs);
print("EQUATION_TERMS " | toString(#terms f));
print("EQUATION " | toString f);
-- torus semi-invariance check: every monomial should have the same row sums and column sums
B = genericMatrix(S, b_0, 3, 3);
mons = apply(terms f, t -> first exponents t);
rowsums = unique apply(mons, e -> apply(3, i -> sum apply(3, j -> e#(3*i+j))));
colsums = unique apply(mons, e -> apply(3, j -> sum apply(3, i -> e#(3*i+j))));
print("ROWSUMS " | toString rowsums | "  COLSUMS " | toString colsums);
-- is f a polynomial in per(B), det(B)?  test membership in the subalgebra they generate at degree 6
perB = sum apply(permutations 3, s -> product apply(3, i -> B_(i, s#i)));
detB = det B;
T = kk[u, v];
-- coefficients c1 per^2 + c2 per*det + c3 det^2 = f ?  solve by linear algebra on monomials
cands = {perB^2, perB*detB, detB^2};
Mc = matrix apply(cands, g -> apply(mons, e -> coefficient(S_e, g)));
fc = matrix {apply(mons, e -> coefficient(S_e, f))};
print("IN_SPAN_PER2_PERDET_DET2 " | toString(rank(Mc || fc) == rank Mc));
print("DONE");
