#!/usr/bin/env python3
"""
Session 47 -- the Phase A work list.

Selects the cells that test the exactness conjecture: 0 < h_pad < a and not
already measured.  Cells with h_pad = 0 are EXCLUDED: there mult_red = 0 = h_pad
by Corollary B2 with no computation, so they carry no evidence (see
results/PREREG_s47.md section 0).

Ordering key is N_S (the monomial count), because the census field nchi_lb is
N_S/stab and overestimates the true n_chi badly.  Calibration from session 42's
201 banked cells: build ~ 1.1e-4 s per monomial; solve ~ 3.6e-8 * n_red * nnz_red
seconds per prime.

usage: python3 wk9_s47_todo.py [--md results/s47_todo.md]
"""
import json, os, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUILD_RATE = 1.1e-4          # s per monomial (median over 201 banked cells)

# cells whose mult_red is already on the record
S43_FAMILY = [((13,12,4,1,1,1),8), ((13,8,8,1,1,1),8), ((14,8,7,1,1,1),8),
              ((13,9,7,1,1,1),8), ((11,9,9,1,1,1),8), ((11,10,8,1,1,1),8),
              ((12,10,7,1,1,1),8), ((12,9,8,1,1,1),8), ((13,10,6,1,1,1),8),
              ((16,13,4,1,1,1),9), ((17,12,4,1,1,1),9)]

def measured_already():
    done = set(S43_FAMILY)
    for f in glob.glob(os.path.join(ROOT, 'results', 's42_cells_*.jsonl')) + \
             [os.path.join(ROOT, 'results', 's42_validation.jsonl'),
              os.path.join(ROOT, 'results', 's47_cells.jsonl')]:
        if not os.path.exists(f): continue
        for L in open(f):
            L = L.strip()
            if L:
                r = json.loads(L); done.add((tuple(r['lam']), r['delta']))
    return done

def census():
    out = []
    for fn in ('s42_census.json', 's42_census_weyl.json'):
        for x in json.load(open(os.path.join(ROOT, 'results', fn))):
            if x.get('a') and x.get('h_pad') is not None and x.get('N_S'):
                out.append(x)
    return out

def in_family(x):
    """the six-row (l1,l2,l3,1,1,1) family of session 43's finding."""
    return x['ell'] == 6 and tuple(x['lam'])[3:] == (1, 1, 1)

def targets():
    done = measured_already()
    t = [x for x in census()
         if 0 < x['h_pad'] < x['a'] and (tuple(x['lam']), x['delta']) not in done]
    for x in t:
        x['gap'] = x['a'] - x['h_pad']
        x['fam'] = in_family(x)
        x['build_est'] = round(BUILD_RATE * x['N_S'])
        # n_red <= number of Stab-orbits <= N_S/|Stab| is the only cost bound
        # available before the build.  Measured ratios n_red/(N_S/stab) over this
        # session's cells: 0.18 to 0.82.  Cells with N_S/stab above ~5e4 were out
        # of reach in a session (the solve is O(n_red * nnz_red) per sequence).
        x['nred_ub'] = x['N_S'] // x['stab']
        x['reach'] = 'yes' if x['nred_ub'] <= 50000 else ('marginal' if x['nred_ub'] <= 120000 else 'no')
    t.sort(key=lambda z: z['N_S'])
    return t

def stratify(t, n_waves=4):
    """Wave 1 is the cheapest cells; later waves add shape coverage.  A cell is
    tagged with the coverage slots it fills so the sweep can be steered."""
    for x in t:
        slots = [f"ell{x['ell']}", f"d{x['delta']}", 'FAM' if x['fam'] else 'OUT',
                 'bigA' if x['a'] >= 10 else 'smallA', f"gap{min(x['gap'],5)}"]
        x['slots'] = slots
    return t

if __name__ == '__main__':
    t = stratify(targets())
    md = None
    if '--md' in sys.argv: md = sys.argv[sys.argv.index('--md') + 1]
    from collections import Counter
    print(f"unmeasured cells with 0 < h_pad < a: {len(t)}")
    print('by ell   ', dict(Counter(x['ell'] for x in t)))
    print('by delta ', dict(Counter(x['delta'] for x in t)))
    print('in family', sum(1 for x in t if x['fam']))
    print('a >= 10  ', sum(1 for x in t if x['a'] >= 10))
    if md:
        with open(md, 'w') as f:
            f.write(RENDER(t))
        print('wrote', md)

def RENDER(t):
    L = []
    L.append("# Session 47 — Phase A work list\n")
    L.append("Generated by `analysis/wk9_s47_todo.py` from `results/s42_census.json` and")
    L.append("`results/s42_census_weyl.json`, before any measurement of this session.\n")
    L.append("**Only cells with `0 < h_pad < a` are listed.**  The 162 census cells with")
    L.append("`h_pad = 0` are excluded on purpose: there `mult_red = 0 = h_pad` follows from")
    L.append("Corollary B2 with no computation, so they are theorems, not tests")
    L.append("(`results/PREREG_s47.md` §0).  Cells already on the record — session 42's")
    L.append("banked set, session 43's family, session 45's `δ = 9` rungs — are excluded too.\n")
    L.append("Ordered by `N_S`, the monomial count, which is the honest cost key: the census")
    L.append("field `nchi_lb` is `N_S/stab` and overestimates the true `n_chi` badly")
    L.append("(20444 against a measured 3881 at `(13,10,5,1,1,1,1)_8`).  `build est` is")
    L.append("`N_S/|Stab|`, an upper bound on `n_red` and the only cost bound available before")
    L.append("the build; session 47 measured `n_red/(N_S/|Stab|)` between 0.18 and 0.82.")
    L.append("The solve is `≈ 3.6·10⁻⁸ · n_red · nnz_red` seconds per Wiedemann sequence, and")
    L.append("a cell needs `nullity + 1` of them per prime, so **`reachable` is the column")
    L.append("that matters**: only 4 of these 292 cells have `N_S/|Stab| ≤ 5·10⁴`.  Session 47")
    L.append("abandoned `(11,9,8,2,1,1)_8` (`n_red = 249213`) after the build for this reason.\n")
    L.append(f"**{len(t)} cells.**  The conjecture predicts `mult_red = h_pad` at every one.\n")
    L.append("| # | `λ` | `δ` | `ℓ` | `a` | `h_pad` | gap | `N_S` | Stab | `n_red ≤` | reachable | family |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for i, x in enumerate(t, 1):
        L.append("| %d | `%s` | %d | %d | %d | %d | %d | %s | %d | %s | %s | %s |" % (
            i, str(tuple(x['lam'])).replace(' ', ''), x['delta'], x['ell'], x['a'],
            x['h_pad'], x['gap'], f"{x['N_S']:,}", x['stab'], f"{x['nred_ub']:,}",
            x['reach'], 'yes' if x['fam'] else '—'))
    return "\n".join(L) + "\n"
